# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 码农的世界
subtitle: 博观而约取，厚积而薄发
name: Jacco 
email: Jacco@foxmail.com
location: Shanghai.China
company: 上海携程旅游网
company_url: http://www.ctrip.com/
github_url: https://github.com/HJacco
github_username: HJacco
description: 贫民窟里的百万富翁，一个人最大的财富就是生活的过往经历
favicon: huang.png # Image must be in assets/images
repository: HJacco/HJacco.github.io

host: 0.0.0.0
# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://HJacco.github.io

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata
  - jekyll-octicons
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: 主页

  -
    href: /blog
    label: 博客

  -
    href: /
    label: 主页

  -
    href: /about
    label: 关于

# labels. my blog key words
labels:

  -
    href: /tech
    name: 技术

  -
    href: /trival
    name: 旅游

  -
    href: /delicacy
    name: 美食
    
  -
    href: /collection
    name: 资源收藏

# selected articles
classes:

  -
    href: /tech
    name: 技术
    describe: 独属于码农


  -
    href: /trival
    name: 旅游杂记
    describe: 临清风，对朗月，登山泛水，意酣歌

  -
    href: /delicacy
    name: 美食
    describe: 家庭厨房的意义从不需要被渲染及夸大，它一直都存在着，只需一个恰当的时间，便会体悟到那些和食物交织在一起的珍贵而又细腻的人世记忆。

  -
    href: /collection
    name: 资源收藏
    describe: 资料

cats:

  -
    href: /java
    name: java系列
    describe: 勤修内功

  -
    href: /big-data
    name: 大数据
    describe: 信息爆炸的时代

  -
    href: /arch
    name: 架构师之路
    describe: 架构师的修养	

  -
    href: /other
    name: 常用技术
    describe: 杂七杂八的东西	

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


fav_novel_books: [平凡的世界,鬼吹灯,三体,盗墓笔记,摆渡人]
fav_tech_books: [java并发编程的艺术,Effective java,Netty权威指南第二版,数据结构与算法分析（java语言描述）,重构 改善既有代码的设计,大型网站系统与Java中间件实践]

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的

gitalk:
    owner: hjacco
    repo: blog-comments
    clientID: bb587899c062bfdfc4ec
    clientSecret: 51e789f759ac1be05e8209a7b30ceac478d73578
